; fio-rand-read.job for fiotest

[global]
name=fio-rand-read                                                               

#filename=fio-rand-read
rw=randread
bs=4K
ba=4096
direct=0
#numjobs=32
invalidate=0
group_reporting
                                                                                  
[file1]                                                                          
size=128M
#ioengine=syn
#ioengine=libaio
#ioengine=mmap
#iodepth=1       
